# -*- coding: utf-8 -*-
"""House-price_LR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/146jpPQEBChGwx-gUOBWDpUZ702DBzzly
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from datetime import datetime, timedelta

# import all libraries and dependencies for data visualization
pd.options.display.float_format='{:.4f}'.format
plt.rcParams['figure.figsize'] = [8,8]
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', -1) 
sns.set(style='darkgrid')
import matplotlib.ticker as ticker
import matplotlib.ticker as plticker

# import all libraries and dependencies for machine learning
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.base import TransformerMixin
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import statsmodels.api as sm
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.metrics import r2_score
# Local file path. Please cha
path = '/content/drive/MyDrive/'
file = path + 'Bengaluru_House_Data.csv'
df_auto = pd.read_csv(file)

df_auto.head()

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

data=pd.read_csv('/content/drive/MyDrive/Bengaluru_House_Data.csv')
data
data=data.drop(['area_type','availability','balcony','society'],axis=1)
data

data.isna().sum()

data=data.dropna()
data.isna().sum()

data['size'].unique()

import matplotlib.pyplot as plt
import seaborn as sns
data.describe()
sns.heatmap(data.corr(), annot=True,linewidths=.10)